language: ruby
script: "bundle exec rake spec SPEC_OPTS='--format documentation'"

matrix:
  fast_finish: true
  include:
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.1.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.2.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.3.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.4.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.5.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.6.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.7.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.8.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.9.0"
    - rvm: 2.1.9
      env: PUPPET_GEM_VERSION="~> 4.10.0"
    - rvm: 2.4.0
      env: PUPPET_GEM_VERSION="~> 5.0.0"
    - rvm: 2.4.0
      env: PUPPET_GEM_VERSION="~> 5.1.0"
    - rvm: 2.5.7
      env: PUPPET_GEM_VERSION="~> 6.11.1"


